### ISSUE TITLE
Feature request, no controls

### ISSUE THREAD

**Issue by plagasul** [rasteiner/k3-pagesdisplay-section#13]
Hello,

When using pagesdisplay, the list of pages include controls for visibility and others.

I'd like to be able to not show these controls at times, to make it clear that this is just a non-interactive display.

It may be confusing for people to not be able to sort or add, but be able to change visibility. In particular in combination with a pages field:

![image](https://user-images.githubusercontent.com/13966673/160410854-c341f08f-54cc-400e-a893-3c73446fb851.png)

... in the pages field you can sort, add and remove, but not change visibility and no contextual menu with other options as in pagesdisplay. Conceptually it may be incoherent, if it is for display, it is for display... 

...or we may want to make it so at least, thus the petition to be able to hide those controls if possible.

Thanks

**Comment by rasteiner** [comment]
I agree :)

you might want to check out the [`feat/controls` branch](https://github.com/rasteiner/k3-pagesdisplay-section/archive/refs/heads/feat/controls.zip), and either disable the controls via the new `controls: false` option or only show the status flag via `controls: flag` and let me know if it works for you.

**Comment by rasteiner** [comment]
From the proposed docs:

----

### Disable Controls
In addition to leaving the controls (the status flag and the options dropdown) visible - the default, it's possible to either hide them completely or show only the status flag.

To completely hide the controls:

```yml
sections:
  mysection:
    headline: Siblings
    type: pagesdisplay
    query: page.siblings(false)
    controls: false
```

To show only the status flag:

```yml
sections:
  mysection:
    headline: Siblings
    type: pagesdisplay
    query: page.siblings(false)
    controls: flag
```
