### ISSUE TITLE
support for kirby 3.7+

### ISSUE THREAD

**Issue by jaro-io** [rasteiner/k3-pagesdisplay-section#16]
hey @rasteiner 💡 ✨ 
i was just playing around with the kirby `3.7.0-rc.1` version and it seems like there are some issues with your plugin after upgrading. if you have a minute, it would be super cool if you could have a look at this. the error i am seeing looks like this:

<img width="515" alt="error" src="https://user-images.githubusercontent.com/20298313/173641167-620f667f-3401-4b8c-bbe8-de79247ce865.png">

thank you so much for being part of the kirby world.
your plugins are so good!
🌻 

---

edit 1: fyi, might be related to https://github.com/getkirby/kirby/pull/4247.
edit 2: i guess a **dream coming true** would be if we could use the new `table` layout with your plugin as well. 🥰 

```yml
notes:
  type: pagesdisplay
  layout: table
  columns:
    subheading:
      label: Subtitle
    date:
      label: Date
      type: date
      display: DD.MM.YYYY
    tags:
      label: Tags
      type: tags
```
