### ISSUE TITLE
controls - Setting no longer working with 3.7.

### ISSUE THREAD

**Issue by FynnZW** [rasteiner/k3-pagesdisplay-section#17]
The setting `controls: false` (or "flag") no longer has an effect with Kirby 3.7.
It's still working when downgrading Kirby to 3.6.6.

**Comment by FynnZW** [comment]
Kirby 3.7. uses items as `computed` instead of as a method.
I think I found a solution, please check the PR

**Comment by rasteiner** [comment]
Perfect! Thanks :)

**Comment by jaro-io** [comment]
@rasteiner @FynnZW controls are now reversed on my side.. `off` by default and `on` only with `controls: true`. also `controls: flag` is not working on my side. cant get them to show at all with any of these values. are you experiencing this as well?

**Comment by FynnZW** [comment]
Are you using Kirby 3.7 or 3.6? On Kirby 3.6 it will probably conflict now, downgrading to plugin version `0.2.0` should solve that.

@rasteiner, might make sense to put this in a new minor version `0.3.0`, so a composer upgrade doesn't automatically break older installations.

**Comment by jaro-io** [comment]
@FynnZW `3.7`

**Comment by FynnZW** [comment]
Oh, that's strange. It's working correctly on my installation, with Kirby 3.7.0.2.


Maybe clearing the browser cache will solve it, so the new Plugin-JS gets loaded? Or deleting the `media/panel`-folder? (it gets generated again automatically)

**Comment by rasteiner** [comment]
Indeed strange, I've tested the patch before merging on the latest Kirby (3.7.0.2). Also 0.2.0 already requires Kirby 3.7

If deleting the media cache doesn't work, could you share the blueprint you're using?

**Comment by jaro-io** [comment]
**so sorry** you two! :grimacing: :roll_eyes: the blueprint i was testing this with already had a `controls: false` set. so i actually added a second option accidentally. so i can definitely confirm `controls: false` is working fine haha!

but on my side i can actually see no difference between `controls: false` and `controls: flag`. i’ve never used this option before, i was just curious. but i was expecting to see the little status circle at the end of each row, like with regular `table` layouts. but it’s not there. or is this not what should be happening?

hope i am not again doing something wrong? just tripple checked that the new plugin version `0.2.1` is installed correctly. updated & reinstalled all my composer dependencies. and i am on `kirby 3.7.0.2` as well.

<img width="1212" alt="plugins" src="https://user-images.githubusercontent.com/20298313/178073819-e41f1032-3957-4d77-bc53-22bc4043ab31.png">

```yml
headline: Orders
type: pagesdisplay
layout: table
empty: No order found
status: published
controls: flag
templates:
    - order
sortBy: num desc
search: true
image: false
limit: 20
text: '#{{ page.invoiceNumber }}'
columns:
    orderid:
        label: Order ID
        width: 2/12
    invoicedate:
        label: Order date
        type: date
        display: MMM DD, YYYY h:mm a
        width: 2/12
    name:
        label: Name
        width: 2/12
    email:
        label: Email
        width: 3/12
    total:
        label: Total
        value: '{{ page.formattedSum }}'
        width: 1/12
        align: right
```
<img width="1280" alt="orders" src="https://user-images.githubusercontent.com/20298313/178074757-41fb317b-0d70-44f6-8656-19e3ac97d927.png">
