### ISSUE TITLE
sortBy query

### ISSUE THREAD

**Issue by jaro-io** [rasteiner/k3-pagesdisplay-section#24]
hey @rasteiner ✨ 
i would love to be able to sort the pages in my `pagesdisplay` sections. and pls don’t get me [wrong](https://github.com/rasteiner/k3-pagesdisplay-section/issues/3). i don’t mean manual sorting in the panel, like you can do with the regular `pages` section and `listed` pages. i just mean using `sortBy()` inside the query. like you can use `filterBy()`.

i tried both of these options but none seemed to work:

```yml
section:
    type: pagesdisplay
    sortBy: date desc
    query: page.children

section:
    type: pagesdisplay
    query: page.children.sortBy('date', 'desc')
```

would be loooovely if you could add this!
thank you so much.
😍
