### ISSUE TITLE
Sortable not working

### ISSUE THREAD

**Issue by hotlines-studio** [rasteiner/k3-pagesdisplay-section#3]
First off, great plugin, thanks! I'm trying to display all pages tied to a specific work category (in my example here) and allow this list to be sortable:

```
columns:
  - width: 2/3
    sections:
      categoryPages:
      type: pagesdisplay
      status: listed
      sortable: true
      query: pages.find('work').children.filterBy('selectCategory', page.title)
```

But in the work category page, there is no way to drag and drop / sort the list of projects. Is there another way `sortable: true` can work in the yaml file, or even in the plugin itself?

Thanks!
